// Cascais Places — SINGLE SOURCE OF TRUTH
// 24 originele plekken in Cascais, Estoril, Guincho, Sintra & Lisbon coast.
// Alle views (categories, explore, map) zijn filtered views van deze dataset.

import type { Place } from "./types";
import { IMAGES } from "./images-v2";

const maps = (q: string) =>
  `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q + ", Cascais, Portugal")}`;

function g(id: string): string[] {
  return IMAGES[id] ?? IMAGES.overview;
}

export const places: Place[] = [
  {
    id: "guincho",
    name: "Praia do Guincho",
    shortName: "Guincho",
    type: "Beach",
    vibe: "Nature",
    drukte: 3,
    besteTijd: "Sunset",
    moodTags: ["Active", "Relax"],
    tags: ["SUNSET", "ACTIVE", "HIDDEN"],
    vibeLine: "Wilde wind, eindeloos zand en surfers die de oceaan trotseren.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Vaak winderig — ideaal voor kitesurf, minder voor handdoekje.",
      "Gratis parkeren bovenop de klif.",
      "Koffie bij de surfclub met uitzicht.",
      "Sunset hier is magisch en rustig.",
    ],
    mapLink: maps("Praia do Guincho"),
    coverImage: g("guincho")[0],
    gallery: g("guincho"),
    exploreImage: g("guincho")[1] ?? g("guincho")[0],
    lat: 38.6939,
    lng: -9.4393,
    neighborhood: "Guincho",
    saves: 1842,
    rating: 4.7,
    addedDaysAgo: 120,
    trending: true,
  },
  {
    id: "rainha",
    name: "Praia da Rainha",
    shortName: "Rainha",
    type: "Beach",
    vibe: "Chill",
    drukte: 2,
    besteTijd: "Morning",
    moodTags: ["Relax", "Romantic"],
    tags: ["HIDDEN", "CHILL", "NEW"],
    vibeLine: "Verborgen koninklijke baai tussen de rotsen van Cascais.",
    voorWie: ["chill", "vrienden"],
    tips: [
      "Vroeg bij zijn = helemaal van jou.",
      "Korte afdaling via de rotsen.",
      "Geen strandtent, neem water mee.",
      "Klein maar extreem fotogeniek.",
    ],
    mapLink: maps("Praia da Rainha"),
    coverImage: g("rainha")[0],
    gallery: g("rainha"),
    exploreImage: g("rainha")[1] ?? g("rainha")[0],
    lat: 38.6917,
    lng: -9.4179,
    neighborhood: "Cascais Centrum",
    saves: 982,
    rating: 4.8,
    addedDaysAgo: 14,
  },
  {
    id: "tamariz",
    name: "Praia do Tamariz",
    shortName: "Tamariz",
    type: "Beach",
    vibe: "Social",
    drukte: 5,
    besteTijd: "Morning",
    moodTags: ["Hype", "Relax"],
    tags: ["SOCIAL", "LUXURY", "TRENDING"],
    vibeLine: "De sociale hotspot met palmen, muziek en ligbedden.",
    voorWie: ["social", "vrienden"],
    tips: [
      "Kom voor 11:00 voor een plekje.",
      "Zwembad direct naast het strand.",
      "Casino Estoril op loopafstand.",
      "Verwacht weekenddrukte.",
    ],
    mapLink: maps("Praia do Tamariz Estoril"),
    coverImage: g("tamariz")[0],
    gallery: g("tamariz"),
    exploreImage: g("tamariz")[1] ?? g("tamariz")[0],
    lat: 38.7058,
    lng: -9.4133,
    neighborhood: "Estoril",
    saves: 2410,
    rating: 4.4,
    addedDaysAgo: 90,
    trending: true,
  },
  {
    id: "cresmina",
    name: "Praia da Cresmina",
    shortName: "Cresmina",
    type: "Beach",
    vibe: "Nature",
    drukte: 2,
    besteTijd: "Morning",
    moodTags: ["Relax", "Active"],
    tags: ["HIDDEN", "CHILL"],
    vibeLine: "Stil duinstrand tussen Guincho en de rotsen.",
    voorWie: ["chill", "vrienden"],
    tips: [
      "Houten pad door de duinen.",
      "Minder wind dan Guincho.",
      "Geen bewaking — zwem bewust.",
      "Top voor een ochtendloop.",
    ],
    mapLink: maps("Praia da Cresmina"),
    coverImage: g("cresmina")[0],
    gallery: g("cresmina"),
    exploreImage: g("cresmina")[1] ?? g("cresmina")[0],
    lat: 38.698,
    lng: -9.438,
    neighborhood: "Guincho",
    saves: 634,
    rating: 4.6,
    addedDaysAgo: 60,
  },
  {
    id: "bocainferno",
    name: "Boca do Inferno",
    shortName: "Boca do Inferno",
    type: "Viewpoint",
    vibe: "Social",
    drukte: 4,
    besteTijd: "Sunset",
    moodTags: ["Hype", "Romantic"],
    tags: ["SUNSET", "VIEW", "SOCIAL", "TRENDING"],
    vibeLine: "Brullende kliffen waar de oceaan zich in stukken slaat.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Bekijk vanaf het houten uitkijkplatform.",
      "Café boven voor sunset met bier.",
      "Parkeer langs de weg.",
      "Indrukwekkend bij harde zee.",
    ],
    mapLink: maps("Boca do Inferno"),
    coverImage: g("bocainferno")[0],
    gallery: g("bocainferno"),
    exploreImage: g("bocainferno")[1] ?? g("bocainferno")[0],
    lat: 38.6906,
    lng: -9.4324,
    neighborhood: "Cascais Centrum",
    saves: 2103,
    rating: 4.6,
    addedDaysAgo: 100,
    trending: true,
  },
  {
    id: "cabodaroca",
    name: "Cabo da Roca",
    shortName: "Cabo da Roca",
    type: "Viewpoint",
    vibe: "Nature",
    drukte: 4,
    besteTijd: "Sunset",
    moodTags: ["Romantic", "Active"],
    tags: ["SUNSET", "VIEW", "HIDDEN"],
    vibeLine: "Meest westelijke punt van Europa — einde van de wereld.",
    voorWie: ["vrienden", "chill"],
    tips: [
      "Neem een trui mee, altijd winderig.",
      "Certificaat te koop bij bezoekerscentrum.",
      "Bus vanuit Sintra en Cascais.",
      "Gouden uur = fotografie paradijs.",
    ],
    mapLink: maps("Cabo da Roca"),
    coverImage: g("cabodaroca")[0],
    gallery: g("cabodaroca"),
    exploreImage: g("cabodaroca")[1] ?? g("cabodaroca")[0],
    lat: 38.7803,
    lng: -9.4945,
    neighborhood: "Sintra",
    saves: 3201,
    rating: 4.9,
    addedDaysAgo: 200,
  },
  {
    id: "santamarta",
    name: "Farol de Santa Marta",
    shortName: "Farol Sta. Marta",
    type: "Viewpoint",
    vibe: "Chill",
    drukte: 3,
    besteTijd: "Sunset",
    moodTags: ["Romantic", "Relax"],
    tags: ["SUNSET", "VIEW", "CHILL"],
    vibeLine: "Witte vuurtoren met museum en de mooiste lichtval van de baai.",
    voorWie: ["chill", "vrienden"],
    tips: [
      "Klein museum, snel bekeken.",
      "Loop de pier naar het uiteinde.",
      "Vang de sunset achter de vuurtoren.",
      "Combineer met het oude centrum.",
    ],
    mapLink: maps("Farol Museu de Santa Marta"),
    coverImage: g("santamarta")[0],
    gallery: g("santamarta"),
    exploreImage: g("santamarta")[1] ?? g("santamarta")[0],
    lat: 38.6915,
    lng: -9.4173,
    neighborhood: "Cascais Centrum",
    saves: 1340,
    rating: 4.7,
    addedDaysAgo: 110,
  },
  {
    id: "casaguia",
    name: "Casa da Guia",
    shortName: "Casa da Guia",
    type: "Viewpoint",
    vibe: "Luxury",
    drukte: 3,
    besteTijd: "Sunset",
    moodTags: ["Romantic", "Relax"],
    tags: ["SUNSET", "VIEW", "LUXURY", "CHILL", "TRENDING"],
    vibeLine: "Klipcafés met terras boven de oceaan en de beste taart.",
    voorWie: ["chill", "vrienden"],
    tips: [
      "Reserveer een terrasplek bij sunset.",
      "Probeer de huisgemaakte taart.",
      "Boutiques op de klif.",
      "Korte prachtige kustwandeling.",
    ],
    mapLink: maps("Casa da Guia"),
    coverImage: g("casaguia")[0],
    gallery: g("casaguia"),
    exploreImage: g("casaguia")[1] ?? g("casaguia")[0],
    lat: 38.686,
    lng: -9.436,
    neighborhood: "Guincho",
    saves: 1890,
    rating: 4.6,
    addedDaysAgo: 50,
    trending: true,
  },
  {
    id: "forte",
    name: "Forte do Guincho",
    shortName: "Forte do Guincho",
    type: "Viewpoint",
    vibe: "Nature",
    drukte: 2,
    besteTijd: "Sunset",
    moodTags: ["Romantic", "Active"],
    tags: ["VIEW", "HIDDEN", "SUNSET", "LUXURY"],
    vibeLine: "17e-eeuws fort met een roekeloos uitzicht over de Atlantische Oceaan.",
    voorWie: ["vrienden", "chill"],
    tips: [
      "Restaurant binnen voor fine dining.",
      "Bereikbaar te voet langs het pad.",
      "Weinig mensen, veel rust.",
      "Combineer met Guincho-strand.",
    ],
    mapLink: maps("Forte do Guincho"),
    coverImage: g("forte")[0],
    gallery: g("forte"),
    exploreImage: g("forte")[1] ?? g("forte")[0],
    lat: 38.69,
    lng: -9.44,
    neighborhood: "Guincho",
    saves: 760,
    rating: 4.8,
    addedDaysAgo: 80,
  },
  {
    id: "miradouro",
    name: "Miradouro Santa Catarina",
    shortName: "Sta. Catarina",
    type: "Viewpoint",
    vibe: "Chill",
    drukte: 3,
    besteTijd: "Sunset",
    moodTags: ["Relax", "Romantic"],
    tags: ["VIEW", "SUNSET", "CHILL", "HIDDEN"],
    vibeLine: "Uitzichtpunt over de baai met de beste gratis sunset van de stad.",
    voorWie: ["chill", "vrienden"],
    tips: [
      "Neem een drankje mee vanaf de supermarkt.",
      "Muurtje om op te zitten.",
      "Minder druk dan Boca do Inferno.",
      "Korte klim vanuit de jachthaven.",
    ],
    mapLink: maps("Miradouro Santa Catarina Cascais"),
    coverImage: g("miradouro")[0],
    gallery: g("miradouro"),
    exploreImage: g("miradouro")[1] ?? g("miradouro")[0],
    lat: 38.6939,
    lng: -9.4179,
    neighborhood: "Cascais Centrum",
    saves: 540,
    rating: 4.5,
    addedDaysAgo: 30,
  },
  {
    id: "mercado",
    name: "Mercado da Vila",
    shortName: "Mercado da Vila",
    type: "Food",
    vibe: "Food",
    drukte: 4,
    besteTijd: "Morning",
    moodTags: ["Hype", "Relax"],
    tags: ["FOOD", "SOCIAL", "TRENDING"],
    vibeLine: "Kleurrijke markt vol verse vis, kaas en Portugese happers.",
    voorWie: ["social", "familie"],
    tips: [
      "Zaterdag = grootste markt.",
      "Probeer de bacalhau pastéis.",
      "Boodschappentas meenemen.",
      "Vers fruit voor het strand.",
    ],
    mapLink: maps("Mercado da Vila Cascais"),
    coverImage: g("mercado")[0],
    gallery: g("mercado"),
    exploreImage: g("mercado")[1] ?? g("mercado")[0],
    lat: 38.6935,
    lng: -9.424,
    neighborhood: "Cascais Centrum",
    saves: 1670,
    rating: 4.6,
    addedDaysAgo: 95,
    trending: true,
  },
  {
    id: "marisco",
    name: "Marisco Vivo",
    shortName: "Marisco Vivo",
    type: "Food",
    vibe: "Food",
    drukte: 3,
    besteTijd: "Night",
    moodTags: ["Hype", "Relax"],
    tags: ["FOOD", "LUXURY", "SOCIAL"],
    vibeLine: "Vers uit zee: gegrilde gambas, cataplana en een glas vinho verde.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Reserveer voor het sunset-terras.",
      "Probeer de cataplana voor twee.",
      "Vinho verde erbij.",
      "Loop vanuit de marina.",
    ],
    mapLink: maps("Seafood restaurant Cascais marina"),
    coverImage: g("marisco")[0],
    gallery: g("marisco"),
    exploreImage: g("marisco")[1] ?? g("marisco")[0],
    lat: 38.6962,
    lng: -9.4145,
    neighborhood: "Cascais Centrum",
    saves: 1230,
    rating: 4.7,
    addedDaysAgo: 70,
  },
  {
    id: "pastelaria",
    name: "Pastelaria Victoria",
    shortName: "Pastelaria",
    type: "Food",
    vibe: "Food",
    drukte: 3,
    besteTijd: "Morning",
    moodTags: ["Relax"],
    tags: ["FOOD", "HIDDEN", "NEW"],
    vibeLine: "Warme pastéis de nata en bica — de ochtendroutine van locals.",
    voorWie: ["familie", "chill"],
    tips: [
      "Best warm uit de oven.",
      "Bica = Portugese espresso.",
      "Goedkoper dan toeristenplekken.",
      "Neem een doosje mee naar huis.",
    ],
    mapLink: maps("Pastelaria Cascais old town"),
    coverImage: g("pastelaria")[0],
    gallery: g("pastelaria"),
    exploreImage: g("pastelaria")[1] ?? g("pastelaria")[0],
    lat: 38.6978,
    lng: -9.4218,
    neighborhood: "Cascais Centrum",
    saves: 890,
    rating: 4.8,
    addedDaysAgo: 10,
  },
  {
    id: "brunch",
    name: "Heim Cascais",
    shortName: "Heim Brunch",
    type: "Food",
    vibe: "Social",
    drukte: 4,
    besteTijd: "Morning",
    moodTags: ["Hype", "Relax"],
    tags: ["FOOD", "SOCIAL", "TRENDING", "NEW"],
    vibeLine: "Aesthetische brunch hotspot met avocado, matcha en natuurlijke wijn.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Reserveer voor weekendbrunch.",
      "Probeer de sourdough pancakes.",
      "Matcha latte is een must.",
      "Instagram-waardig interieur.",
    ],
    mapLink: maps("Heim Cascais brunch"),
    coverImage: g("brunch")[0],
    gallery: g("brunch"),
    exploreImage: g("brunch")[1] ?? g("brunch")[0],
    lat: 38.6939,
    lng: -9.4218,
    neighborhood: "Cascais Centrum",
    saves: 1450,
    rating: 4.5,
    addedDaysAgo: 20,
    trending: true,
  },
  {
    id: "rooftop",
    name: "Rooftop Lounge",
    shortName: "Rooftop",
    type: "Food",
    vibe: "Luxury",
    drukte: 3,
    besteTijd: "Sunset",
    moodTags: ["Romantic", "Hype"],
    tags: ["SUNSET", "LUXURY", "SOCIAL", "VIEW"],
    vibeLine: "Dakterras met oneindig uitzicht op de oceaan en signature cocktails.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Sunset = reserveren verplicht.",
      "Probeer de gin tonica.",
      "Dresscode smart chic.",
      "Happy hour 17-19u.",
    ],
    mapLink: maps("Rooftop bar Cascais"),
    coverImage: g("rooftop")[0],
    gallery: g("rooftop"),
    exploreImage: g("rooftop")[1] ?? g("rooftop")[0],
    lat: 38.697,
    lng: -9.4185,
    neighborhood: "Cascais Centrum",
    saves: 1620,
    rating: 4.6,
    addedDaysAgo: 35,
    trending: true,
  },
  {
    id: "casino",
    name: "Casino Estoril",
    shortName: "Casino Estoril",
    type: "Event",
    vibe: "Luxury",
    drukte: 4,
    besteTijd: "Night",
    moodTags: ["Hype"],
    tags: ["SOCIAL", "LUXURY"],
    vibeLine: "Glamour, gokken en shows in Europa's grootste casino.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Nette kleding verplicht.",
      "Shows en diner in het complex.",
      "Tamariz-strand op loopafstand.",
      "Parkeer onder het casino.",
    ],
    mapLink: maps("Casino Estoril"),
    coverImage: g("casino")[0],
    gallery: g("casino"),
    exploreImage: g("casino")[1] ?? g("casino")[0],
    lat: 38.7057,
    lng: -9.396,
    neighborhood: "Estoril",
    saves: 1120,
    rating: 4.3,
    addedDaysAgo: 150,
  },
  {
    id: "festival",
    name: "Festival do Mar",
    shortName: "Festival do Mar",
    type: "Event",
    vibe: "Social",
    drukte: 5,
    besteTijd: "Night",
    moodTags: ["Hype"],
    tags: ["SOCIAL", "FOOD", "TRENDING"],
    vibeLine: "Zomernachten vol live muziek, streetfood en dansende menigten.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Zomermaanden = seizoen actief.",
      "Cash meenemen voor foodtrucks.",
      "Kom vroeg voor een plek vooraan.",
      "Combineer met een avond in het centrum.",
    ],
    mapLink: maps("Cascais bay promenade events"),
    coverImage: g("festival")[0],
    gallery: g("festival"),
    exploreImage: g("festival")[1] ?? g("festival")[0],
    lat: 38.6942,
    lng: -9.4172,
    neighborhood: "Cascais Centrum",
    saves: 2010,
    rating: 4.5,
    addedDaysAgo: 15,
    trending: true,
  },
  {
    id: "marina",
    name: "Cascais Marina",
    shortName: "Marina",
    type: "Chill",
    vibe: "Luxury",
    drukte: 3,
    besteTijd: "Night",
    moodTags: ["Relax", "Hype"],
    tags: ["CHILL", "LUXURY", "SOCIAL"],
    vibeLine: "Witte jachten, flanerende mensen en terrasjes met uitzicht.",
    voorWie: ["social", "chill"],
    tips: [
      "Avondwandeling langs de boten.",
      "Sushi met sunset view.",
      "Veilig en relaxt.",
      "Combineer met het oude centrum.",
    ],
    mapLink: maps("Cascais Marina"),
    coverImage: g("marina")[0],
    gallery: g("marina"),
    exploreImage: g("marina")[1] ?? g("marina")[0],
    lat: 38.696,
    lng: -9.414,
    neighborhood: "Cascais Centrum",
    saves: 1080,
    rating: 4.5,
    addedDaysAgo: 85,
  },
  {
    id: "parque",
    name: "Parque Marechal Carmona",
    shortName: "Parque Carmona",
    type: "Chill",
    vibe: "Nature",
    drukte: 2,
    besteTijd: "Morning",
    moodTags: ["Relax", "Romantic"],
    tags: ["CHILL", "HIDDEN"],
    vibeLine: "Groene oase met pauwen, picknickplekken en schaduw.",
    voorWie: ["familie", "chill"],
    tips: [
      "Ideaal voor een ochtendwandeling.",
      "Picknick meenemen.",
      "Kinderen houden van de pauwen.",
      "Gratis en rustig.",
    ],
    mapLink: maps("Parque Marechal Carmona"),
    coverImage: g("parque")[0],
    gallery: g("parque"),
    exploreImage: g("parque")[1] ?? g("parque")[0],
    lat: 38.6928,
    lng: -9.4258,
    neighborhood: "Cascais Centrum",
    saves: 620,
    rating: 4.6,
    addedDaysAgo: 130,
  },
  {
    id: "promenade",
    name: "Passeio Marítimo",
    shortName: "Boulevard",
    type: "Chill",
    vibe: "Social",
    drukte: 3,
    besteTijd: "Sunset",
    moodTags: ["Relax", "Romantic"],
    tags: ["CHILL", "SOCIAL", "SUNSET"],
    vibeLine: "De boulevard waar heel Cascais flaneert bij zonsondergang.",
    voorWie: ["familie", "social"],
    tips: [
      "Fietsen te huur bij de jachthaven.",
      "IJssalon onderweg.",
      "Loop door naar Boca do Inferno.",
      "Gouden uur langs het water.",
    ],
    mapLink: maps("Passeio Maritimo Cascais"),
    coverImage: g("promenade")[0],
    gallery: g("promenade"),
    exploreImage: g("promenade")[1] ?? g("promenade")[0],
    lat: 38.694,
    lng: -9.417,
    neighborhood: "Cascais Centrum",
    saves: 1410,
    rating: 4.7,
    addedDaysAgo: 60,
  },
  {
    id: "oldtown",
    name: "Centro Histórico",
    shortName: "Centrum",
    type: "Shopping",
    vibe: "Social",
    drukte: 4,
    besteTijd: "Night",
    moodTags: ["Hype", "Relax"],
    tags: ["SOCIAL", "FOOD", "TRENDING"],
    vibeLine: "Smalle straatjes, pastelhuizen en terrasjes die nooit slapen.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Avond = levendig en fotogeniek.",
      "Probeer een ginjinha.",
      "Winkels sluiten laat.",
      "Verdwaal in de zijstraatjes.",
    ],
    mapLink: maps("Centro Historico Cascais"),
    coverImage: g("oldtown")[0],
    gallery: g("oldtown"),
    exploreImage: g("oldtown")[1] ?? g("oldtown")[0],
    lat: 38.6975,
    lng: -9.4215,
    neighborhood: "Cascais Centrum",
    saves: 2560,
    rating: 4.7,
    addedDaysAgo: 180,
    trending: true,
  },
  {
    id: "hike",
    name: "Costa do Guincho Trail",
    shortName: "Coastal Trail",
    type: "Activity",
    vibe: "Nature",
    drukte: 2,
    besteTijd: "Morning",
    moodTags: ["Active", "Romantic"],
    tags: ["ACTIVE", "HIDDEN", "VIEW"],
    vibeLine: "Klippenwandeling langs wilde kust met de oceaan op elke stap.",
    voorWie: ["vrienden", "chill"],
    tips: [
      "Start vroeg voor schaduw en rust.",
      "Stevige schoenen verplicht.",
      "Neem voldoende water mee.",
      "Prachtige foto-stops onderweg.",
    ],
    mapLink: maps("Guincho coastal trail Cascais"),
    coverImage: g("hike")[0],
    gallery: g("hike"),
    exploreImage: g("hike")[1] ?? g("hike")[0],
    lat: 38.6955,
    lng: -9.4378,
    neighborhood: "Guincho",
    saves: 690,
    rating: 4.8,
    addedDaysAgo: 55,
  },
  {
    id: "surf",
    name: "Guincho Surf School",
    shortName: "Surf School",
    type: "Activity",
    vibe: "Social",
    drukte: 3,
    besteTijd: "Morning",
    moodTags: ["Active", "Hype"],
    tags: ["ACTIVE", "SOCIAL", "TRENDING"],
    vibeLine: "Les in de branding met wetsuit en board — voor beginners en doorgevers.",
    voorWie: ["vrienden", "social"],
    tips: [
      "Boek de vroege ochtend-les.",
      "Wetsuit en board inbegrepen.",
      "Groepslessen goedkoper.",
      "Douches en lockers aanwezig.",
    ],
    mapLink: maps("Guincho surf school Cascais"),
    coverImage: g("surf")[0],
    gallery: g("surf"),
    exploreImage: g("surf")[1] ?? g("surf")[0],
    lat: 38.6942,
    lng: -9.4395,
    neighborhood: "Guincho",
    saves: 880,
    rating: 4.7,
    addedDaysAgo: 28,
    trending: true,
  },
  {
    id: "sintra",
    name: "Palácio da Pena",
    shortName: "Sintra",
    type: "Museum",
    vibe: "Luxury",
    drukte: 5,
    besteTijd: "Morning",
    moodTags: ["Romantic", "Active"],
    tags: ["VIEW", "LUXURY", "TRENDING"],
    vibeLine: "Sprookjeskasteel boven de mist van de Serra — een must daytrip.",
    voorWie: ["familie", "vrienden"],
    tips: [
      "Boek tickets online voor tijds slot.",
      "Neem de 434 bus vanaf het station.",
      "Kom bij opening voor minder drukte.",
      "Wandel naar de hoogste toren.",
    ],
    mapLink: maps("Palacio da Pena Sintra"),
    coverImage: g("sintra")[0],
    gallery: g("sintra"),
    exploreImage: g("sintra")[1] ?? g("sintra")[0],
    lat: 38.7864,
    lng: -9.3906,
    neighborhood: "Sintra",
    saves: 4120,
    rating: 4.9,
    addedDaysAgo: 300,
    trending: true,
  },
  {
    id: "beachclub",
    name: "Atlantic Beach Club",
    shortName: "Beach Club",
    type: "Chill",
    vibe: "Luxury",
    drukte: 4,
    besteTijd: "Sunset",
    moodTags: ["Hype", "Relax"],
    tags: ["LUXURY", "SOCIAL", "CHILL", "TRENDING"],
    vibeLine: "Ligbedden, pool en DJ-sets boven de oceaan — zomer in stijl.",
    voorWie: ["social", "vrienden"],
    tips: [
      "Reserveer een cabana.",
      "Minimum besteding.",
      "Happy hour 16-18u.",
      "Zonsondergang met DJ.",
    ],
    mapLink: maps("Beach club Cascais"),
    coverImage: g("beachclub")[0],
    gallery: g("beachclub"),
    exploreImage: g("beachclub")[1] ?? g("beachclub")[0],
    lat: 38.6905,
    lng: -9.4192,
    neighborhood: "Cascais Centrum",
    saves: 1820,
    rating: 4.5,
    addedDaysAgo: 38,
    trending: true,
  },
];

export const HERO_IMAGE = IMAGES.overview[0];
export const HERO_IMAGES = IMAGES.overview;
export const EXPLORE_HEADER_IMAGE = IMAGES.overview[1] ?? IMAGES.overview[0];

export function getPlace(id: string): Place | undefined {
  return places.find((p) => p.id === id);
}
